### ISSUE TITLE
Architectural change needed

### ISSUE THREAD

**Issue by afouille** [gnugat-legacy/SoulMeMaybe#6]
Hi,

SoulMeMaybe works perfectly for me. Unfortunately, I've found an architectural problem impeding the professional advancement of this project. In a kindly spirit, I open this issue for you. I would appreciate quickness in your answer.

What was my surprise when I saw that it happened that SoulMeMaybe was not written in a programming language. I'm sure you know that a software needs to be written in a programming language. It's a little difficult for a software to works when it's not written in a programming language. Any programming language would be appropriate. C/C++/Python would be good, but even C# or worse, Java, would be correct.

Thank you and hoping that this issue would be answered soon,

**Comment by gnugat** [comment]
Hi, thanks for this report.
Unfortunately, this issue is already known as it occurred to me before the beginning of the project, when I asked myself: `What programming language should I choose?`.

This simple questions (only 42 characters) has haunted my for nearly 8 years before I could come up with an answer.
As a matter of fact, C, C++, java and Python were fighting precisely in that order inside my head to win the project:
1. C would be the fastest, but the code would have been pretty ugly without Object Oriented design;
2. C++ would be great for performance and is object oriented, but I would have to manually support many plateforms;
3. Java, while being less efficient, is object oriented and is multi-plateform, but the code would have been ugly;
4. Python has the same traits as Java, is beautiful, but nobody uses it so nobody would help...

I decided to go on a trip and went to Canada to learn how the maple syrup runs on trees, to Czech Republic to analyze how old housing at moderated rents are presented as 5 star hotels, to England to private myself from good food in order to gain higher spiritual capacity and to Ireland to flood my failure in a lot of guiness.

When I went back home, I was a different man, I had finally the capacity to decide which programing language would be best. I had to choose a sneaky one which would steal its force from the others, which would stab them in the back to grow more powerful.

There is only one [pirate language](http://blog.astrumfutura.com/2012/04/php-innocent-villagefolk-or-a-pillagin-pirate/) who can do that: PHP.

A scripting language like PHP might seem a bit cranky, but it's what the develop do that defines the code, not the chosen language. Moreover, libraries/frameworks like Symfony2 and composer gave a new, clean, real OOP and exciting dimension to PHP.

**Comment by afouille** [comment]
Hi,

Thank you for this insight into the decision process for the programming language of SoulMeMaybe. I appreciate your sincerity when you said you were drunk on Guiness, food deprived, and homeless in Czech Republic when you made this choice. It explains everything.

When you explained PHP steals its force from the others, did you mean the life force, or the soul? Anyway, all my prayers are with you for your day-to-day dealing with this abomination. May God be with you when the Devil will ask to take his due.

**Comment by gnugat** [comment]
Heads up! [The following commit](https://github.com/gnugat/SoulMeMaybe/commit/306063d9a795b5ea5aa938ae3be8940d205b22f1) describes one of the favorite thing a C developer like you loves: meaningless and insignificant optimization.

This means that despite of being written in PHP, **SoulMeMaybe** now surpasses Java and Python projects in term of efficiency, and is now up to the level of C and C++ applications!

This, plus the use of [minimalist Dependency Injection Container like Pimple](http://pimple.sensiolabs.org/) and of caching system for the configuration which are planned for the 2.0.0 version definitely fix the architectural problems, so I'm closing this issue.

Thanks for the report!
